import type { Metadata } from 'next'
import './globals.css'
import { League_Spartan } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const leagueSpartan = League_Spartan({ subsets: ['latin'], weight: ['700'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={leagueSpartan.className}>{children}</body>
    </html>
  )
}
